### PR TITLE
Some small changes that I needed in the counterfactual resimulator.

### PR DESCRIPTION
**Pull request by jonathan-laurent**

### CODE REVIEW

**Comment by pirbo** [comment]
Salut,
- I've pushed commits that does not raised any question.
- It would be nice if TQL could compile against KaSim4 Would back port only 4dc0e45a7ea2e62b47425210038efbca65335b46 be enough to make that append? (If so I'll do it)
- 2 questions:
 * Code: In 018893a903100a57356031ec1e801a785c0b75fe `try_concretize_tests` is "useless" because there cannot be `Fresh` agents in tests (so `Not_found` cannot be raised) but this is an invariant not enforced by types so I agree it is a bit dangerous to rely on it. I don't know what to do? Do you have an opinion.
* Design:
First `maxConsecutiveClash` in `Genric_rule_interpreter.apply_rule` should be renamed `maxConsecutiveNull` as it consider all kind of null events not only clashes. This clarification being made, It looks like you choose to not consider `Blocked` as a null event. Is it important to distinguish it? I would suggest to make `incr_consecutive_blocked` increment also `t.consecutive` and to not add a specific `?maxConsecutiveBlocked` to `apply_rule` bu if you have good reason to not do that, I'm OK with it.

**Comment by jonathan-laurent** [comment]
Thanks Pierre for considering my pull request so quickly. I will answer your questions in order.
-  The commit you quoted is indeed all that is necessary for the TQL to compile with KaSim 4. In fact, the only recent major change in KaSim was about syntax and the TQL has its own parser anyway (which I updated). Ultimately, it would be good for the TQL to use on Kasim's parser though.
- I am fine with both solutions: keeping or removing try_concretize_tests. If you want to remove it, there should be only one line to update in Generic_rule_interpreter.ml.
- Blocked events should not be considered as "normal" null events that result from failures of the rectangular approximation. Indeed, after three consecutive null events happen, it is very likely to be safe to enumerate all instances as there should not be too many of them (without which getting three consecutive null events would have been very unlikely). This is not true anymore in the case of blocked events. A binding rule with many instances may be blocked three times in a row, and still have so many instances that it would be unfeasible to enumerate them. Therefore, how many consecutive blocked events to tolerate has to be decided by more subtle heuristics.

PS: Can I still contact you on your Harvard email ? If not, can you send me the new one ?

**Comment by pirbo** [comment]
Sorry I did not used the merge button of github because I did not pushed commits all at once (and in order) but I think they are all is in master now (and the relevant commit has been pack ported to KaSim4), don't they?

**Comment by jonathan-laurent** [comment]
Yes, every commit was pulled. Thanks!

**Pull request closed without merging**
