### PR TITLE
Update packaging Makefile rules using Electron.js instead of NWJS

### PR DESCRIPTION
**Pull request by yvan-sraka**
https://electronjs.org/

This experiment was firstly motivated by finding a workaround to deal with the "blur" bug [1] (on Apple retina displays).

I discover by comparing Electron default `Info.plist` and the one generated by `Info.plist.skel` that we lack the property:

	<key>NSHighResolutionCapable</key>
	<true/>

as explained in this old documentation: https://developer.apple.com/library/archive/documentation/GraphicsAnimation/Conceptual/HighResolutionOSX/Explained/Explained.html

The choice of switching from NWJS to Electron was motivated by the:
- good support of Electron by community and Microsoft
- native capabilities API we let us implement in a near futur:
	* automatic updates (eg. from GitHub releases)
	* crash reports (eg. to GitHub issues)

[1] To visualize the "blur" bug, here are two screenshots (taken on Macbook Pro 13', with default scale for display, in full screen mode):

- before (this patch):

- after:

### CODE REVIEW

**Comment by pirbo** [comment]
Amazing! Thanks!
But we need to care about linux and windows too now.
As you've modified `js/package.json`, we can't use nwjs anymore (and that's good!) so we need to update the Makefile rules `Kappapp.tar.gz` and `KappaBin.zip` in order to reach a state in which it is possible to start the kappapp by a double click on these platforms too.

**Comment by jkrivine** [comment]
This is soo great. Using the app under mac os x makes me feel myopic...

**Comment by yvan-sraka** [comment]
@pirbo I updated the PR with new `Kappapp.tar.gz` and `KappaBin.zip` rules, I completely removed all appearance of NWJS here!

- I used the x64 version of electron (https://github.com/electron/electron/releases), I don’t know if there is some 32bits or ARM based users of Kappa, it could maybe be an issue?
- I also suggest packaging the app using https://flatpak.org/ on Linux, what do you think about it? (it could be done in another PR)

:warning: I tested it on Linux but not on Windows, since the build is broken on it!

**Comment by yvan-sraka** [comment]
I post here the few documentation links about how to implement with Electron:
- auto update: https://electronjs.org/docs/api/auto-updater
- crash report: https://electronjs.org/docs/api/crash-reporter
- file association: https://www.electron.build/configuration/configuration#PlatformSpecificBuildOptions-fileAssociations (this could help to fix https://github.com/Kappa-Dev/KaSim/issues/548)

**Comment by yvan-sraka** [comment]
\o/ !!

**Pull request merged**
